name = "zero-ad"
main = "src/index.ts"
compatibility_date = "2024-02-21"
compatibility_flags = ["nodejs_compat"]

# Replace with your Cloudflare Account ID
account_id = "fe408e9ce02645d28107a1d33b3f38a2"

# KV Namespace Binding
[[kv_namespaces]]
binding = "ADBLOCK_KV"
id = "f8b49529055b49ac9900e85c1f27c974"

[vars]
# Internal name for API calls
SCRIPT_NAME = "zero-ad"
# List Source URLs (Comma-separated)
ADBLOCK_LIST_URLS = "https://raw.githubusercontent.com/sander85/uBO-et/main/list.txt,https://small.oisd.nl"
# Maximum items per list (Free: 1000, Enterprise: 5000)
MAX_ITEMS_PER_LIST = 1000
# Prefix for Gateway Lists created by this worker
LIST_PREFIX = "AdBlock_Worker_"
# Maximum number of lists to manage (Free limit is ~100 lists total)
MAX_LISTS = 90
CLOUDFLARE_ACCOUNT_ID = "fe408e9ce02645d28107a1d33b3f38a2"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1

